const VOCAB_DATA = {
  words: [
    {w: "Abend", m: "evening", c: 32},
    {w: "Abenteuer", m: "adventure", c: 11},
    {w: "Abfahren", m: "to depart", c: 32},
    {w: "Abgrund", m: "abyss", c: 96},
    {w: "Abhängen", m: "to depend", c: 32},
    {w: "Abnehmen", m: "to remove", c: 32},
    {w: "Absagen", m: "to cancel", c: 32},
    {w: "Abschied", m: "farewell", c: 32},
    {w: "Abschnitt", m: "section", c: 32},
    {w: "Abstimmen", m: "to vote", c: 32},
    {w: "An", m: "at / to (vertical surface, two-way)", c: 57},
    {w: "Angst", m: "anxiety/dread", c: 13},
    {w: "Ankündigung", m: "announcement", c: 97},
    {w: "Anschrift", m: "address", c: 18},
    {w: "Apfel", m: "apple", c: 3},
    {w: "Arbeit", m: "work", c: 10},
    {w: "Art", m: "kind/type", c: 84},
    {w: "Arzt", m: "doctor", c: 5},
    {w: "Auf", m: "on / onto (horizontal surface, two-way)", c: 57},
    {w: "Aufbruch", m: "new beginning", c: 25},
    {w: "Aufklärung", m: "enlightenment", c: 19},
    {w: "Augenblick", m: "moment", c: 18},
    {w: "Ausdruck", m: "expression", c: 18},
    {w: "Auswirkung", m: "impact", c: 95},
    {w: "Baum", m: "tree", c: 2},
    {w: "Bedeutung", m: "meaning", c: 18},
    {w: "Bedingung", m: "condition", c: 19},
    {w: "Beichte", m: "confession", c: 16},
    {w: "Beobachtung", m: "observation", c: 95},
    {w: "Bereitschaft", m: "readiness", c: 37},
    {w: "Berichterstattung", m: "reporting", c: 97},
    {w: "Berücksichtigung", m: "consideration", c: 95},
    {w: "Bewusstsein", m: "consciousness", c: 19},
    {w: "Bibel", m: "Bible", c: 15},
    {w: "Bildung", m: "education", c: 35},
    {w: "Billion", m: "trillion", c: 84},
    {w: "Brot", m: "bread", c: 2},
    {w: "Bruder", m: "brother", c: 1},
    {w: "Buch", m: "book", c: 8},
    {w: "Buchstabe", m: "letter", c: 14},
    {w: "Bürger", m: "citizen", c: 10},
    {w: "Dame", m: "lady", c: 11},
    {w: "Dampf", m: "steam", c: 21},
    {w: "Dankbar", m: "grateful", c: 38},
    {w: "Darstellung", m: "presentation", c: 95},
    {w: "Dem", m: "dative article (masc./neut.)", c: 54},
    {w: "Den", m: "the (masc. acc.)", c: 53},
    {w: "Deutsch", m: "German (language)", c: 15},
    {w: "Dich", m: "you", c: 53},
    {w: "Dichtung", m: "dense poetry", c: 20},
    {w: "Dir", m: "to you, for you (dative, informal)", c: 54},
    {w: "Dorf", m: "village", c: 7},
    {w: "Druckerpresse", m: "printing press", c: 14},
    {w: "Dürfen", m: "to be allowed", c: 52},
    {w: "Ehre", m: "honour", c: 9},
    {w: "Eigenschaft", m: "quality", c: 37},
    {w: "Eigentlich", m: "actually", c: 98},
    {w: "Eindruck", m: "impression", c: 31},
    {w: "Einen", m: "a (masc. acc.)", c: 53},
    {w: "Einfach", m: "simple", c: 31},
    {w: "Einfluss", m: "influence", c: 31},
    {w: "Eingang", m: "entrance", c: 31},
    {w: "Einheit", m: "unity", c: 21},
    {w: "Einkaufen", m: "to shop", c: 31},
    {w: "Einladen", m: "to invite", c: 31},
    {w: "Einsamkeit", m: "loneliness", c: 36},
    {w: "Einschlafen", m: "to fall asleep", c: 31},
    {w: "Einschränkung", m: "restriction", c: 97},
    {w: "Einverstanden", m: "agreed", c: 31},
    {w: "Eisenbahn", m: "railway", c: 21},
    {w: "Endlösung", m: "final solution", c: 24},
    {w: "Entdeckung", m: "discovery", c: 22},
    {w: "Entfremdung", m: "alienation", c: 21},
    {w: "Entscheidung", m: "decision", c: 35},
    {w: "Erbe", m: "inheritance", c: 6},
    {w: "Erde", m: "earth", c: 2},
    {w: "Erfahrung", m: "experience", c: 19},
    {w: "Erinnerung", m: "memory", c: 24},
    {w: "Erscheinung", m: "appearance", c: 19},
    {w: "Ewigkeit", m: "eternity", c: 96},
    {w: "Fabrik", m: "factory", c: 84},
    {w: "Feder", m: "quill", c: 8},
    {w: "Fenster", m: "window", c: 4},
    {w: "Fernweh", m: "distance-sickness", c: 20},
    {w: "Feuer", m: "fire", c: 1},
    {w: "Fisch", m: "fish", c: 3},
    {w: "Flucht", m: "flight/escape", c: 17},
    {w: "Flugblatt", m: "pamphlet", c: 16},
    {w: "Flugzeug", m: "airplane", c: 33},
    {w: "Forderung", m: "demand", c: 97},
    {w: "Forschung", m: "research", c: 22},
    {w: "Forschungsergebnis", m: "research result", c: 95},
    {w: "Freiheit", m: "freedom", c: 15},
    {w: "Fremder", m: "stranger", c: 6},
    {w: "Freundlich", m: "friendly", c: 38},
    {w: "Freundschaft", m: "friendship", c: 37},
    {w: "Frieden", m: "peace", c: 13},
    {w: "Furchtbar", m: "terrible", c: 38},
    {w: "Fuß", m: "foot", c: 3},
    {w: "Fähigkeit", m: "ability", c: 36},
    {w: "Ge- + Stem + -t", m: "Regular past participle pattern", c: 58},
    {w: "Gebet", m: "prayer", c: 13},
    {w: "Geborgenheit", m: "shelter", c: 96},
    {w: "Gefallen", m: "to please, to like", c: 54},
    {w: "Gefährlich", m: "dangerous", c: 38},
    {w: "Gegangen", m: "gone (past participle irregular)", c: 58},
    {w: "Gegenstand", m: "object", c: 19},
    {w: "Gegenwart", m: "present", c: 26},
    {w: "Gelassenheit", m: "serenity", c: 13},
    {w: "Geld", m: "money", c: 10},
    {w: "Gelegenheit", m: "opportunity", c: 36},
    {w: "Gemacht", m: "made (past participle regular)", c: 58},
    {w: "Gemütlichkeit", m: "cozy warmth", c: 20},
    {w: "Genau", m: "exactly", c: 98},
    {w: "Gesehen", m: "seen (past participle irregular)", c: 58},
    {w: "Gesellschaft", m: "society", c: 37},
    {w: "Gesundheit", m: "health", c: 36},
    {w: "Gewissen", m: "conscience", c: 15},
    {w: "Gewürz", m: "spice", c: 12},
    {w: "Gift", m: "poison", c: 83},
    {w: "Glaube", m: "faith", c: 13},
    {w: "Gott", m: "God", c: 8},
    {w: "Grenze", m: "border", c: 5},
    {w: "Grundlage", m: "foundation", c: 95},
    {w: "Haben", m: "have (auxiliary for most verbs)", c: 58},
    {w: "Hafen", m: "harbor", c: 12},
    {w: "Handel", m: "trade", c: 10},
    {w: "Handschuh", m: "glove", c: 33},
    {w: "Handy", m: "mobile phone", c: 26},
    {w: "Haus", m: "house", c: 2},
    {w: "Heimat", m: "homeland", c: 6},
    {w: "Heimweh", m: "homesickness", c: 20},
    {w: "Held", m: "hero", c: 9},
    {w: "Helfen", m: "to help (+ dative)", c: 54},
    {w: "Herz", m: "heart", c: 3},
    {w: "Hochdeutsch", m: "standard German", c: 18},
    {w: "Hoffnung", m: "hope", c: 11},
    {w: "Hund", m: "hound", c: 2},
    {w: "Hunger", m: "hunger", c: 17},
    {w: "Ihm", m: "to him, for him (dative)", c: 54},
    {w: "Ihn", m: "him", c: 53},
    {w: "Immerhin", m: "nonetheless", c: 98},
    {w: "In", m: "in / into (two-way)", c: 57},
    {w: "Inseparable Prefixes", m: "No ge- prefix (be-, er-, ver-, etc.)", c: 58},
    {w: "Irgendwie", m: "somehow", c: 98},
    {w: "Jedenfalls", m: "in any case", c: 98},
    {w: "Kaffee", m: "coffee", c: 12},
    {w: "Kaiser", m: "emperor", c: 4},
    {w: "Kampf", m: "battle", c: 9},
    {w: "Kapital", m: "capital", c: 21},
    {w: "Karawane", m: "caravan", c: 12},
    {w: "Keller", m: "cellar", c: 5},
    {w: "Ketzer", m: "heretic", c: 16},
    {w: "Kindergarten", m: "children\'s garden", c: 22},
    {w: "Kirche", m: "church", c: 6},
    {w: "Kloster", m: "cloister", c: 8},
    {w: "Krankenhaus", m: "hospital", c: 33},
    {w: "Krankheit", m: "sickness", c: 22},
    {w: "Kreuz", m: "cross", c: 5},
    {w: "Krieg", m: "war", c: 6},
    {w: "Käse", m: "cheese", c: 4},
    {w: "König", m: "king", c: 6},
    {w: "Können", m: "to be able", c: 51},
    {w: "Küche", m: "kitchen", c: 4},
    {w: "Kühlschrank", m: "fridge", c: 33},
    {w: "Land", m: "land", c: 6},
    {w: "Landschaft", m: "landscape", c: 37},
    {w: "Leidenschaft", m: "passion", c: 37},
    {w: "Lesen", m: "to read", c: 14},
    {w: "Liebe", m: "love", c: 11},
    {w: "Lied", m: "song", c: 9},
    {w: "Lustig", m: "funny", c: 38},
    {w: "Mannschaft", m: "team", c: 37},
    {w: "Markt", m: "market", c: 5},
    {w: "Maschine", m: "machine", c: 21},
    {w: "Mauer", m: "wall", c: 4},
    {w: "Maßnahme", m: "measure", c: 97},
    {w: "Mehrwert", m: "surplus value", c: 21},
    {w: "Meinung", m: "opinion", c: 35},
    {w: "Meister", m: "master", c: 5},
    {w: "Mich", m: "me", c: 53},
    {w: "Milch", m: "milk", c: 2},
    {w: "Minnelied", m: "love song", c: 11},
    {w: "Mir", m: "to me, for me (dative)", c: 54},
    {w: "Mit", m: "with (+ dative)", c: 54},
    {w: "Mundart", m: "dialect", c: 18},
    {w: "Mutter", m: "mother", c: 1},
    {w: "Märchen", m: "fairy tale", c: 20},
    {w: "Möchten", m: "would like", c: 52},
    {w: "Mögen", m: "to like", c: 52},
    {w: "Möglich", m: "possible", c: 38},
    {w: "Möglichkeit", m: "possibility", c: 36},
    {w: "Mönch", m: "monk", c: 8},
    {w: "Münze", m: "coin", c: 5},
    {w: "Müssen", m: "to must", c: 51},
    {w: "Nachhaltigkeit", m: "sustainability", c: 26},
    {w: "Nacht", m: "night", c: 1},
    {w: "Name", m: "name", c: 1},
    {w: "Nie wieder", m: "never again", c: 24},
    {w: "Note", m: "grade/mark", c: 84},
    {w: "Ordnung", m: "order", c: 35},
    {w: "Ostalgie", m: "nostalgia for the East", c: 25},
    {w: "Papier", m: "paper", c: 14},
    {w: "Pergament", m: "parchment", c: 8},
    {w: "Pest", m: "plague", c: 13},
    {w: "Pfeffer", m: "pepper", c: 7},
    {w: "Pfeil", m: "arrow", c: 5},
    {w: "Pferd", m: "horse", c: 7},
    {w: "Pflanze", m: "plant", c: 7},
    {w: "Pforte", m: "gate", c: 4},
    {w: "Pfund", m: "pound", c: 7},
    {w: "Plündern", m: "to plunder", c: 17},
    {w: "Predigt", m: "sermon", c: 16},
    {w: "Promotion", m: "PhD", c: 84},
    {w: "Quasi", m: "as if", c: 98},
    {w: "Rat", m: "advice", c: 83},
    {w: "Rechtschreibung", m: "spelling", c: 18},
    {w: "Regen", m: "rain", c: 2},
    {w: "Reise", m: "journey", c: 12},
    {w: "Rente", m: "pension", c: 84},
    {w: "Richtung", m: "direction", c: 35},
    {w: "Ritter", m: "knight", c: 11},
    {w: "Ruhig", m: "calm", c: 38},
    {w: "Schach", m: "chess", c: 12},
    {w: "Schiff", m: "ship", c: 7},
    {w: "Schild", m: "shield", c: 9},
    {w: "Schildkröte", m: "turtle", c: 33},
    {w: "Schlagzeug", m: "drums", c: 33},
    {w: "Schlussfolgerung", m: "conclusion", c: 95},
    {w: "Schrift", m: "writing", c: 8},
    {w: "Schuld", m: "guilt/debt", c: 16},
    {w: "Schule", m: "school", c: 4},
    {w: "Schweigen", m: "silence", c: 24},
    {w: "Schwert", m: "sword", c: 9},
    {w: "Schwester", m: "sister", c: 1},
    {w: "Schönheit", m: "beauty", c: 36},
    {w: "Seele", m: "soul", c: 8},
    {w: "Sehnsucht", m: "yearning", c: 20},
    {w: "Seide", m: "silk", c: 12},
    {w: "Sein", m: "be (auxiliary for motion/change)", c: 58},
    {w: "Seite", m: "page", c: 14},
    {w: "Sicherheit", m: "safety", c: 36},
    {w: "Sohn", m: "son", c: 9},
    {w: "Soldat", m: "soldier", c: 17},
    {w: "Sollen", m: "to should", c: 52},
    {w: "Sonderbehandlung", m: "special treatment", c: 24},
    {w: "Sowieso", m: "anyway", c: 98},
    {w: "Sozusagen", m: "so to speak", c: 98},
    {w: "Spaltung", m: "schism/split", c: 16},
    {w: "Sprache", m: "language", c: 14},
    {w: "Sprachreiniger", m: "language purifier", c: 18},
    {w: "Stadt", m: "city", c: 10},
    {w: "Stahl", m: "steel", c: 21},
    {w: "Stamm", m: "tribe", c: 6},
    {w: "Staubsauger", m: "vacuum", c: 33},
    {w: "Stein", m: "stone", c: 2},
    {w: "Stellungnahme", m: "position", c: 95},
    {w: "Sterben", m: "to die", c: 13},
    {w: "Stern", m: "star", c: 1},
    {w: "Stille", m: "silence", c: 13},
    {w: "Stimmung", m: "attunement", c: 20},
    {w: "Straße", m: "street", c: 4},
    {w: "Streit", m: "dispute", c: 16},
    {w: "Sünde", m: "sin", c: 16},
    {w: "Tatsächlich", m: "actually", c: 98},
    {w: "Tinte", m: "ink", c: 8},
    {w: "Tisch", m: "table", c: 5},
    {w: "Tod", m: "death", c: 9},
    {w: "Traurig", m: "sad", c: 38},
    {w: "Treue", m: "loyalty", c: 9},
    {w: "Trost", m: "comfort", c: 13},
    {w: "Turnier", m: "tournament", c: 11},
    {w: "Unheimlich", m: "uncanny", c: 22},
    {w: "Unter", m: "under / beneath (two-way)", c: 57},
    {w: "Untergang", m: "downfall", c: 22},
    {w: "Vater", m: "father", c: 1},
    {w: "Verantwortung", m: "responsibility", c: 24},
    {w: "Vergangenheit", m: "past", c: 26},
    {w: "Vergänglichkeit", m: "transience", c: 96},
    {w: "Verhandlung", m: "negotiation", c: 97},
    {w: "Vernunft", m: "reason", c: 19},
    {w: "Verständigung", m: "understanding", c: 26},
    {w: "Verwandlung", m: "transformation", c: 96},
    {w: "Verwüstung", m: "devastation", c: 17},
    {w: "Volk", m: "people", c: 6},
    {w: "Vor", m: "before / in front of (two-way)", c: 57},
    {w: "Voraussetzung", m: "precondition", c: 95},
    {w: "Vorstellung", m: "idea", c: 19},
    {w: "Vorwurf", m: "accusation", c: 97},
    {w: "Wahrheit", m: "truth", c: 15},
    {w: "Wald", m: "wold/forest", c: 2},
    {w: "Waldeinsamkeit", m: "forest solitude", c: 20},
    {w: "Wand", m: "wall", c: 84},
    {w: "Wanderlust", m: "desire to wander", c: 20},
    {w: "Wandern", m: "to wander", c: 6},
    {w: "Wappen", m: "coat of arms", c: 7},
    {w: "Waren", m: "goods", c: 12},
    {w: "Wasser", m: "water", c: 1},
    {w: "Weg", m: "way/path", c: 6},
    {w: "Wein", m: "wine", c: 4},
    {w: "Weltanschauung", m: "worldview", c: 22},
    {w: "Weltschmerz", m: "world-pain", c: 20},
    {w: "Wende", m: "the turning point", c: 25},
    {w: "Wichtig", m: "important", c: 38},
    {w: "Widerstand", m: "resistance", c: 24},
    {w: "Wiedervereinigung", m: "reunification", c: 25},
    {w: "Willkommen", m: "welcome", c: 26},
    {w: "Wirklichkeit", m: "reality", c: 19},
    {w: "Wirtschaft", m: "economy", c: 37},
    {w: "Wissen", m: "knowledge", c: 14},
    {w: "Wissenschaft", m: "science", c: 22},
    {w: "Wo?", m: "Where? (location → dative)", c: 57},
    {w: "Wohin?", m: "Where to? (motion → accusative)", c: 57},
    {w: "Wohnung", m: "apartment", c: 35},
    {w: "Wollen", m: "to want", c: 51},
    {w: "Wort", m: "word", c: 1},
    {w: "Wunderbar", m: "wonderful", c: 38},
    {w: "Wörterbuch", m: "dictionary", c: 18},
    {w: "Zahnbürste", m: "toothbrush", c: 33},
    {w: "Zeile", m: "line of text", c: 14},
    {w: "Zeit", m: "time", c: 7},
    {w: "Zeitgeist", m: "spirit of age", c: 22},
    {w: "Zeitung", m: "newspaper", c: 35},
    {w: "Zerrissenheit", m: "torn-ness", c: 96},
    {w: "Zerstörung", m: "destruction", c: 17},
    {w: "Ziegel", m: "brick", c: 4},
    {w: "Zu", m: "to, at (+ dative)", c: 54},
    {w: "Zucker", m: "sugar", c: 12},
    {w: "Zuhause", m: "at home", c: 26},
    {w: "Zukunft", m: "future", c: 26},
    {w: "Zunft", m: "guild", c: 10},
    {w: "Zusammenarbeit", m: "cooperation", c: 26},
    {w: "Zusammenfassung", m: "summary", c: 95},
    {w: "Zusammenhang", m: "context", c: 19},
    {w: "Zusammenwachsen", m: "growing together", c: 25},
    {w: "aktuell", m: "current", c: 83},
    {w: "allerdings", m: "concession", c: 87},
    {w: "also", m: "so/therefore", c: 84},
    {w: "arbeiten", m: "to work", c: 50},
    {w: "befehlen", m: "to command", c: 81},
    {w: "bekommen", m: "to receive", c: 83},
    {w: "bergen", m: "to rescue", c: 81},
    {w: "beweisen", m: "to prove", c: 79},
    {w: "binden", m: "to bind", c: 80},
    {w: "bleiben", m: "to remain", c: 79},
    {w: "brav", m: "obedient", c: 83},
    {w: "brechen", m: "to break", c: 81},
    {w: "das Buch", m: "book", c: 47},
    {w: "das Fenster", m: "window", c: 47},
    {w: "das Messer", m: "knife", c: 47},
    {w: "der Löffel", m: "spoon", c: 47},
    {w: "der Schrank", m: "cupboard", c: 47},
    {w: "der Stuhl", m: "chair", c: 47},
    {w: "der Tisch", m: "table", c: 47},
    {w: "die Gabel", m: "fork", c: 47},
    {w: "die Lampe", m: "lamp", c: 47},
    {w: "die Tür", m: "door", c: 47},
    {w: "doch", m: "contradiction", c: 85},
    {w: "drei", m: "three", c: 3},
    {w: "du bist", m: "you are", c: 48},
    {w: "du hast", m: "you have", c: 49},
    {w: "eben", m: "inevitability", c: 86},
    {w: "eigentlich", m: "hedging", c: 87},
    {w: "empfehlen", m: "to recommend", c: 81},
    {w: "empfinden", m: "to feel", c: 80},
    {w: "entscheiden", m: "to decide", c: 79},
    {w: "er/sie/es hat", m: "he/she/it has", c: 49},
    {w: "er/sie/es ist", m: "he/she/it is", c: 48},
    {w: "erschrecken", m: "to be frightened", c: 81},
    {w: "essen", m: "eat", c: 3},
    {w: "eventuell", m: "possibly", c: 83},
    {w: "fahren", m: "to drive", c: 82},
    {w: "fallen", m: "to fall", c: 82},
    {w: "fangen", m: "to catch", c: 82},
    {w: "fast", m: "almost", c: 84},
    {w: "finden", m: "to find", c: 80},
    {w: "fragen", m: "to ask", c: 50},
    {w: "geben", m: "to give", c: 82},
    {w: "gehabt", m: "had", c: 49},
    {w: "gehen", m: "to go", c: 82},
    {w: "gelingen", m: "to succeed", c: 80},
    {w: "gelten", m: "to be valid", c: 81},
    {w: "gewesen", m: "been", c: 48},
    {w: "gewinnen", m: "to win", c: 80},
    {w: "grün", m: "green", c: 2},
    {w: "haben", m: "to have", c: 49},
    {w: "halt", m: "resignation", c: 86},
    {w: "halten", m: "to hold", c: 82},
    {w: "helfen", m: "to help", c: 81},
    {w: "ich bin", m: "I am", c: 48},
    {w: "ich habe", m: "I have", c: 49},
    {w: "ihr habt", m: "you (plural) have", c: 49},
    {w: "ihr seid", m: "you (plural) are", c: 48},
    {w: "ja", m: "assumption", c: 85},
    {w: "jedenfalls", m: "return", c: 87},
    {w: "kaufen", m: "to buy", c: 10},
    {w: "kommen", m: "to come", c: 82},
    {w: "lassen", m: "to let", c: 82},
    {w: "laufen", m: "to run", c: 82},
    {w: "leihen", m: "to lend", c: 79},
    {w: "lernen", m: "to learn", c: 50},
    {w: "lesen", m: "to read", c: 82},
    {w: "machen", m: "make", c: 3},
    {w: "mal", m: "softener", c: 85},
    {w: "meiden", m: "to avoid", c: 79},
    {w: "nehmen", m: "to take", c: 81},
    {w: "nämlich", m: "explanation", c: 87},
    {w: "offen", m: "open", c: 7},
    {w: "preisen", m: "to praise", c: 79},
    {w: "reiben", m: "to rub", c: 79},
    {w: "reich", m: "rich", c: 12},
    {w: "ringen", m: "to wrestle", c: 80},
    {w: "rufen", m: "to call", c: 82},
    {w: "sagen", m: "to say", c: 50},
    {w: "scheinen", m: "to seem", c: 79},
    {w: "schlafen", m: "to sleep", c: 82},
    {w: "schon", m: "reassurance", c: 86},
    {w: "schreiben", m: "to write", c: 5},
    {w: "schreien", m: "to shout", c: 79},
    {w: "schweigen", m: "to be silent", c: 79},
    {w: "schwimmen", m: "to swim", c: 80},
    {w: "schwinden", m: "to fade", c: 80},
    {w: "sehen", m: "to see", c: 82},
    {w: "sein", m: "to be", c: 48},
    {w: "sensibel", m: "reactive", c: 83},
    {w: "sie/Sie haben", m: "they/you (formal) have", c: 49},
    {w: "sie/Sie sind", m: "they/you (formal) are", c: 48},
    {w: "singen", m: "to sing", c: 80},
    {w: "sinken", m: "to sink", c: 80},
    {w: "spenden", m: "to donate", c: 84},
    {w: "spielen", m: "to play", c: 50},
    {w: "sprechen", m: "to speak", c: 81},
    {w: "springen", m: "to jump", c: 80},
    {w: "stehen", m: "to stand", c: 82},
    {w: "stehlen", m: "to steal", c: 81},
    {w: "steigen", m: "to climb", c: 79},
    {w: "sterben", m: "to die", c: 81},
    {w: "suchen", m: "to search", c: 50},
    {w: "sympathisch", m: "likeable", c: 83},
    {w: "tragen", m: "to carry", c: 82},
    {w: "treffen", m: "to meet", c: 81},
    {w: "treiben", m: "to drive", c: 79},
    {w: "trinken", m: "to drink", c: 80},
    {w: "tun", m: "to do", c: 82},
    {w: "verderben", m: "to ruin", c: 81},
    {w: "verkaufen", m: "to sell", c: 10},
    {w: "vermeiden", m: "to avoid (prevent)", c: 79},
    {w: "verschwinden", m: "to disappear", c: 80},
    {w: "wachsen", m: "to grow", c: 82},
    {w: "war", m: "was", c: 48},
    {w: "waschen", m: "to wash", c: 82},
    {w: "weisen", m: "to point", c: 79},
    {w: "werben", m: "to court", c: 81},
    {w: "werfen", m: "to throw", c: 81},
    {w: "winden", m: "to wind", c: 80},
    {w: "wir haben", m: "we have", c: 49},
    {w: "wir sind", m: "we are", c: 48},
    {w: "wohnen", m: "to live", c: 50},
    {w: "zehn", m: "ten", c: 3},
    {w: "zeigen", m: "to show", c: 50},
    {w: "ziehen", m: "to pull", c: 82},
    {w: "zwingen", m: "to force", c: 80},
    {w: "Über", m: "over / above (two-way)", c: 57},
    {w: "Überhaupt", m: "at all", c: 98},
    {w: "Überleben", m: "to survive", c: 17},
    {w: "Übung", m: "practice", c: 35},
    {w: "übrigens", m: "aside", c: 87}
  ],
  patterns: [
    {p: "Sound Shifts", d: "gh→ch, th→d, sw→schw, V→F, st→sht, sp→shp. These consistent transformations unlock the connection between English and German words.", c: 1},
    {p: "Grimm\'s Law", d: "Systematic consonant correspondences showing that sound changes follow predictable patterns, not random chaos.", c: 1},
    {p: "Shared PIE Roots", d: "Mutter/mother, Vater/father, Nacht/night, and Schwester/sister all reveal a common ancestry in Proto-Indo-European.", c: 1},
    {p: "German Pronunciation", d: "V sounds like F (Vater = \"Fahter\"), st sounds like sht (Stern = \"shtern\"). These pronunciation rules are as important as spelling.", c: 1},
    {p: "The Decoder Ring", d: "Once you know the patterns, you can predict thousands of German words from English. The key to understanding is recognizing that difference follows la", c: 1},
    {p: "Germanic strong verbs", d: "The Germanic peoples invented a new verb system: sing/sang/sung, drink/drank/drunk. These \"ablaut\" patterns don\'t exist in Latin or Greek. They are un", c: 2},
    {p: "Forest vocabulary cognates", d: "Words born in the Germanic forests remain almost identical across English and German: Wald/wold, Baum/beam, Stein/stone, Regen/rain, grün/green. The s", c: 2},
    {p: "Settlement vocabulary cognates", d: "When the Germanic peoples settled, they created words for home life that both languages kept: Haus/house, Brot/bread, Milch/milk, Erde/earth, Hund/hou", c: 2},
    {p: "Environment drives language", d: "Proto-Indo-European on the open steppe became Proto-Germanic in the dense forests. Same people, new world, new language. The pattern repeats throughou", c: 2},
    {p: "First Consonant Shift (500 BCE)", d: "p→f, t→th/d, k→h. This shift affected all Germanic languages equally and created the first major divide between Germanic and other Indo-European langu", c: 3},
    {p: "Second Consonant Shift (600-800 CE)", d: "p→pf/f, t→ss/z, k→ch. This shift happened only in High German (southern regions) and created the modern distinction between German and English.", c: 3},
    {p: "The Benrath Line", d: "The geographic boundary between High German (full shifts) and Low German (first shift only). This explains why modern German looks so different from E", c: 3},
    {p: "Decoding Power of the Shifts", d: "English word → Apply the shifts → Predict the German form. Foot becomes Fuß, fish becomes Fisch, three becomes drei. The shifts are predictable and sy", c: 3},
    {p: "Why German Looks Different", d: "English stopped after the First Shift; German kept going through the Second. This double shift explains why German spelling and sound seem alien to En", c: 3},
    {p: "Latin words for Roman technologies", d: "The Germanic peoples borrowed words for things they did not have: wine, roads, walls, windows, tiles.", c: 4},
    {p: "Asymmetric borrowing", d: "Rome borrowed nothing from Germanic; the flow was one direction only.", c: 4},
    {p: "Grammaticalization", d: "Latin words became fully German, with German gender, German endings, German pronunciation.", c: 4},
    {p: "Caesar becomes Kaiser", d: "The name of Rome\'s greatest general became the Germanic word for emperor, showing how names become titles become institutions.", c: 4},
    {p: "Power in language", d: "Borrowing patterns reveal power dynamics: the weaker culture borrows from the stronger.", c: 4},
    {p: "Frontier Borrowing", d: "400 years of contact along the limes created a linguistic laboratory where words crossed the border constantly.", c: 5},
    {p: "Slavic Influence", d: "Grenze itself comes from Slavic granica, showing Germany\'s eastern linguistic frontier too.", c: 5},
    {p: "Multiple Contact Zones", d: "German absorbed from Latin, Slavic, and Greek — not just one source of borrowing.", c: 5},
    {p: "Cultural Exchange", d: "Trade vocabulary flows across borders: Markt, Münze, Arzt all show practical contact and cultural transmission.", c: 5},
    {p: "The Limes as Membrane", d: "The Roman frontier was porous, not a wall — a place where languages grew richer through contact.", c: 5},
    {p: "The Power of Migration", d: "When peoples scatter, languages diverge. The same word spoken in different lands evolves differently. One voice becomes many.", c: 6},
    {p: "The Loan Word", d: "When cultures meet, languages borrow from each other. Kirche comes from Greek kyriakón, brought by Christian missionaries.", c: 6},
    {p: "The Core Vocabulary", d: "The most ancient words survive the longest. Mutter, Feuer, Wasser, Weg, Land — these words were spoken in Gothic in 350 CE and are still spoken in Ger", c: 6},
    {p: "The Emotional Vocabulary", d: "Some words capture the spirit of an era. Heimat carries the ache of displacement. Fremder carries the identity crisis of migration. Language remembers", c: 6},
    {p: "The Second Germanic Consonant Shift", d: "A systematic transformation that happened in southern German regions (500-800 CE), creating the divide between High German and Low German, and explain", c: 7},
    {p: "P → PF/FF/F", d: "The most visible shift, affecting every word with an initial \'p\' in the shifted regions. This alone accounts for dozens of German words that seem alie", c: 7},
    {p: "T → TS/SS/Z", d: "The second major shift, transforming \'t\' sounds into affricate and fricative forms. Time becomes Zeit, Tide remains Tide.", c: 7},
    {p: "K → CH/H", d: "The third shift, often combining with other sounds. Make becomes Machen, Ship (from sk-) becomes Schiff.", c: 7},
    {p: "The Benrath Line", d: "A geographic boundary marking where the shifts took place and where they did not. South of the line: German with all shifts. North of the line: Dutch ", c: 7},
    {p: "Monastic Writing", d: "monks first wrote German down, making permanent what had only been spoken. Writing forced decisions: spelling, grammar, vocabulary all had to be stand", c: 8},
    {p: "The Abrogans", d: "~765 CE, earliest German glossary. The first systematic collection of German words, preserved by monks who understood the value of the language they s", c: 8},
    {p: "Latin → German", d: "religious words entered through the church. Kirche from Greek kyriaké. Kloster from Latin claustrum. Language reflects power: conquerors\' words become", c: 8},
    {p: "Writing as Preservation", d: "oral language becomes permanent record. Before writing, words lived only in memory and voice. After writing, they could outlive the speaker, the centu", c: 8},
    {p: "Oral → Written", d: "The Hildebrandslied was sung for centuries before monks wrote it down around 820 CE. This marks the boundary between oral tradition (living, changing,", c: 9},
    {p: "Compound Words", d: "Old High German builds complex meanings by stacking roots.", c: 9},
    {p: "Warrior Vocabulary", d: "Schwert (sword), Schild (shield), Kampf (battle), Held (hero), Tod (death), Ehre (honor). These words reveal what mattered to Old High German culture:", c: 9},
    {p: "Language Preserves", d: "The poem is the only surviving Old High German epic. But it shows us that old languages don\'t disappear—they transform. Every word in the Hildebrandsl", c: 9},
    {p: "Commerce Language", d: "kaufen, verkaufen, Handel — trade vocabulary that emerged when German towns became economic centers. The medieval marketplace created an explosion of ", c: 10},
    {p: "Compound Power", d: "Marktplatz (market+place), Handelshaus (trade+house), Zunftmeister (guild+master). German\'s compound-word genius shines in commerce: every concept can", c: 10},
    {p: "Latin Integration", d: "Meister (from Latin magister) shows how thoroughly German absorbed foreign words and made them feel completely native. Not borrowed—integrated.", c: 10},
    {p: "Social Structure → Words", d: "Bürger (citizen, from Burg = castle/town), Zunft (guild). New classes needed new vocabulary. The rise of the merchant class created language that Engl", c: 10},
    {p: "French borrowings in courtly vocabulary", d: "Turnier, Dame, Abenteuer shaped medieval German during the courtly period (1150-1250), brought by Crusades and cultural contact.", c: 11},
    {p: "Suffix -ung creates abstract nouns", d: "hoffen → Hoffnung, sammeln → Sammlung. This productive pattern remains one of German\'s most generative word-building tools.", c: 11},
    {p: "Emotional vocabulary stays Germanic", d: "While Turnier and Dame came from France, Liebe, Herz, Treue, and Hoffnung are purely Germanic, reflecting an inner emotional life.", c: 11},
    {p: "Minnesang tradition fused languages", d: "Poetry that combined French courtly themes with Germanic word-building power, creating a new literary register.", c: 11},
    {p: "German absorbs without losing identity", d: "French words adopted into German take on German grammar (gender, plurals, compounds), becoming invisible immigrants within the language.", c: 11},
    {p: "Arabic borrowings for exotic goods", d: "Zucker (sugar), Kaffee (coffee), Schach (chess), Karawane (caravan) entered German during Crusades and Hanseatic trade (1200-1400), reflecting contact", c: 12},
    {p: "Germanic/PIE roots for commerce", d: "Hafen (harbor), Waren (goods), reich (rich), Reise (journey) remain Germanic and deeply rooted, showing that even in trade, native words held their gr", c: 12},
    {p: "Borrowed words become fully German", d: "Foreign words absorbed completely into German grammar (gender, plurals, compounds). Zucker takes German forms: der Zucker, die Zucker, Zuckerdose, Kaf", c: 12},
    {p: "Word geography traces culture routes", d: "Seide (silk) traveled 8,000 km from China via Persia to Latin to German, carrying within it the history of the Silk Road itself.", c: 12},
    {p: "\"Ge-\" prefix as intensifier", d: "Ge-würz (spice) shows how German transforms borrowed concepts by prefixing them with native building blocks, making them visibly German.", c: 12},
    {p: "Crisis Vocabulary", d: "Pest, Sterben, Angst — words born from catastrophe. The vocabulary of the Black Death reveals how language responds to mass mortality, not by borrowin", c: 13},
    {p: "Mystical Coinages", d: "Meister Eckhart invented Gelassenheit (letting-be, serenity), a word that would shape German philosophy for six centuries. A single person can change ", c: 13},
    {p: "Dialect Collapse", d: "40% population loss killed entire dialect regions. Medieval German had far more regional variation than modern German does. Towns separated by only a ", c: 13},
    {p: "Emotional Depth", d: "German words for inner states: Angst (constriction, anxiety), Trost (comfort), Stille (silence), Hoffnung (hope), Glaube (faith), Frieden (peace). The", c: 13},
    {p: "Print Standardisation", d: "Printing froze spelling and spread one dialect across wide territories. Before print, every town wrote German differently. Print demanded consistency ", c: 14},
    {p: "Compound Power", d: "Druckerpresse (press+press), Buchstabe (beech+staff = letter, from runes carved on beech wood) — Germanic word-building combines simple elements into ", c: 14},
    {p: "Technology Vocabulary", d: "Papier, Seite, Zeile — the tools of literacy. Each word carries history: Papier from Egyptian papyrus through Greek and Latin; Seite (page, side) from", c: 14},
    {p: "Chinese Parallel", d: "Bi Sheng invented moveable type ~1040 CE, nearly 400 years before Gutenberg. Yet the same innovation had vastly different impacts: in Chinese, it neve", c: 14},
    {p: "-heit suffix = English -hood/-ness", d: "Wahrheit/truth-ness, Freiheit/free-ness, Gewissen-heit/conscience-ness (state of being)", c: 15},
    {p: "-heit always feminizes", d: "der Mensch (man, masc.), die Menschheit (humanity, fem.)", c: 15},
    {p: "German compound words = Germanic invention", d: "Bluthund, Feuertaufe, Buchstabe (beech-stick) — English has lost this power", c: 15},
    {p: "Luther\'s principle: write as people speak", d: "This created modern German syntax, not Latin syntax", c: 15},
    {p: "Sacred + vernacular = revolution", d: "Latin kept power. German democratized it.", c: 15},
    {p: "The \"-ung\" suffix", d: "Transforms verbs into nouns representing actions or states (spalten→Spaltung, lösen→Lösung, treffen→Treffung)", c: 16},
    {p: "Germanic roots for sacred concepts", d: "Predigt (borrowed from Latin), Beichte (purely Germanic), Sünde (ancient Germanic)", c: 16},
    {p: "The same word, inverted meanings", d: "Ketzer could mean both \"heretical\" and \"chosen as pure\" depending on who spoke it", c: 16},
    {p: "Compound meanings", d: "Schuld merges guilt and debt; Flugblatt merges flight and sheet — German\'s power to build meaning from component parts", c: 16},
    {p: "Religious division creates linguistic division", d: "Streit (dispute) eventually becomes Krieg (war); words no longer bridge gaps but mark them", c: 16},
    {p: "War Vocabulary", d: "Zerstörung, Plündern, Verwüstung — destruction words that intensify devastation through Germanic prefixes.", c: 17},
    {p: "French Court Dominance", d: "150 years of French as prestige language in German courts, nearly extinguishing German as a language of culture and literature.", c: 17},
    {p: "Prefix Power: ver-/zer-", d: "ver-wüsten (transform into wasteland), zer-stören (break apart completely) — intensifying prefixes that build survival vocabulary.", c: 17},
    {p: "Survival Language", d: "Überleben (over+live = survive), Flucht (flight/escape), Frieden (peace) — the vocabulary that remained stubbornly Germanic because the language of su", c: 17},
    {p: "Language Societies", d: "Fruchtbringende Gesellschaft defended German from French dominance through organized, systematic work.", c: 18},
    {p: "Purism Movement", d: "Replacing French loans with Germanic coinages: Zeitschrift (journal), Augenblick (moment), Wörterbuch (dictionary).", c: 18},
    {p: "Compound Elegance", d: "Augenblick (eye+moment = instant), Wörterbuch (word+book = dictionary), Rechtschreibung (right+writing = spelling) — Germanic compounds beat French si", c: 18},
    {p: "Standardisation", d: "Gottsched\'s 1748 grammar codified the rules. Hochdeutsch (High German) emerged as an ideal form above all dialects.", c: 18},
    {p: "Transparent Philosophy", d: "German builds concepts you can see inside. Every philosophical term is transparent: Aufklärung (up+clearing = enlightenment), Bewusstsein (aware+being", c: 19},
    {p: "Prefix Precision", d: "The prefix system creates philosophical exactness: vor- (before, as in Vor-stellung), er- (out of, as in Er-fahrung), zusammen- (together, as in Zusam", c: 19},
    {p: "Why German for Philosophy", d: "Compound power lets you coin exact terms. When Kant needed a word for his philosophy, German could build it from visible parts. Er-fahrung doesn\'t mea", c: 19},
    {p: "Abstract from Concrete", d: "fahren→Erfahrung (travel→experience), wirken→Wirklichkeit (work→reality), stehen→Gegenstand (stand→object). Philosophy in German is philosophy you can", c: 19},
    {p: "Untranslatable Words", d: "Sehnsucht (yearning+addiction = an aching desire for something you may never find), Weltschmerz (world+pain = the gap between how things are and how t", c: 20},
    {p: "Opposite Pairs", d: "Heimweh (home+woe = homesickness) and its mirror Fernweh (far+woe = the longing to be elsewhere). German creates emotional opposites through systemati", c: 20},
    {p: "Grimm\'s Dictionary", d: "The Brothers Grimm began their dictionary in 1838 to preserve this extraordinary vocabulary. It wasn\'t completed until 1961, 123 years later. They und", c: 20},
    {p: "Romantic Compounds", d: "Waldeinsamkeit, Wanderlust — these are feeling-words. German compounds that capture entire emotional states in a single word. This is why German becam", c: 20},
    {p: "Compound words for technology", d: "Eisenbahn (iron+path), Dampfmaschine (steam+machine) show how German builds technical vocabulary from native roots rather than borrowing.", c: 21},
    {p: "Ent- prefix for reversal", d: "Entfremdung (alienation) uses ent- (un-doing) + fremd (foreign) to express \"becoming foreign to oneself,\" a philosophical concept encoded in word stru", c: 21},
    {p: "Mehr- prefix for surplus", d: "Mehrwert (more+value = surplus value) demonstrates how German creates abstract economic terms by compounding simple Germanic roots.", c: 21},
    {p: "Language and political unity", d: "Hochdeutsch became the standard as Germany unified; a shared language was both tool and symbol of Einheit (unity).", c: 21},
    {p: "-schaft suffix creates abstract nouns", d: "Wissenschaft (knowledge+state = science), Gesellschaft (companion+state = society). This productive suffix turns concrete ideas into abstract domains.", c: 22},
    {p: "Un- prefix for negation and dread", d: "Unheimlich (un+homely = uncanny). Freud built an entire theory on this word: the familiar made strange, the homely turned horrifying.", c: 22},
    {p: "Untranslatable compound concepts", d: "Weltanschauung, Zeitgeist, Angst, Kindergarten entered English because no English word could capture the same meaning. German\'s compounding power crea", c: 22},
    {p: "Unter- prefix for descent", d: "Untergang (under+going = downfall, decline). Spengler\'s \"Der Untergang des Abendlandes\" gave the world a word for civilisational decline.", c: 22},
    {p: "Ver- prefix for transformation", d: "Verfremdung (making-strange), Verfassung (constitution = that which is grasped/composed). Ver- transforms root meaning into something altered or inten", c: 23},
    {p: "Gleich- prefix for equality", d: "Gleichberechtigung (equal+rights) shows how German builds social concepts by compounding: same rights, literally. The word structure makes the politic", c: 23},
    {p: "Zusammen- prefix for togetherness", d: "Zusammenbruch (together+break = collapse). When things that were zusammen (together) break, you get catastrophe. The word encodes both the unity and i", c: 23},
    {p: "Language as artistic medium", d: "Gestaltung, Ausdruck, Bühne — Weimar artists treated German words themselves as design objects, shaping meaning through form.", c: 23},
    {p: "Euphemism as weapon", d: "Endlösung (final solution), Sonderbehandlung (special treatment) — the Nazis weaponised German\'s compound precision to disguise atrocity behind bureau", c: 24},
    {p: "Schuld carries double meaning", d: "Schuld means both \"guilt\" and \"debt,\" encoding the idea that guilt is something owed, a moral debt that must be paid. Post-war Germany built an entire", c: 24},
    {p: "Wider- prefix for resistance", d: "Widerstand (against+stand = resistance). The word\'s structure is physical: standing against something. Widerspruch (contradiction), Widerruf (revocati", c: 24},
    {p: "Language after catastrophe", d: "After 1945, German writers questioned whether the language itself was contaminated. Could you write poetry in the language of the perpetrators? Adorno", c: 24},
    {p: "Wieder- prefix for return and repetition", d: "Wiedervereinigung (re+unification), Wiedersehen (seeing again). The prefix wieder encodes the hope of return, of things coming back together.", c: 25},
    {p: "Zusammen- prefix for togetherness", d: "Zusammenwachsen (together+growing) captures the slow organic process of reunification. Not a sudden event but a gradual growing-together.", c: 25},
    {p: "Auf- prefix for upward movement", d: "Aufbruch (up+break = new beginning, departure). When you break upward, you start something new. Aufstieg (rise), Aufklärung (enlightenment) follow the", c: 25},
    {p: "Ostalgie: a neologism from history", d: "Ost (east) + Nostalgie (nostalgia) = a word that could only exist after the Wall fell, capturing longing for a vanished world.", c: 25},
    {p: "Denglisch: English absorption", d: "Handy (mobile phone), downloaden, Laptop — modern German absorbs English words wholesale, but often gives them new meanings (Handy is not English!).", c: 26},
    {p: "Nach- prefix for sustainability", d: "Nachhaltigkeit (after+holding+ness = sustainability). The word literally means \"the quality of holding after\" — ensuring something endures beyond the ", c: 26},
    {p: "Gegen- prefix for presence and opposition", d: "Gegenwart (against+waiting = the present). The present moment is what stands against you, what waits before you. Gegenteil (opposite), Gegenüber (the ", c: 26},
    {p: "Zu- prefix for belonging", d: "Zuhause (to+house = at home), Zukunft (to+coming = future). The future is literally \"what is coming towards you.\"", c: 26},
    {p: "Completion and Intensification", d: "The ver- prefix does not create new concepts but amplifies and completes them. Where stehen means \"to stand,\" verstehen means to stand fully and compl", c: 27},
    {p: "Semantic Reversal", d: "In some verbs, ver- inverts the meaning entirely. To forbid is the opposite of to offer, yet verbieten emerges from bieten through the prefix. This sh", c: 27},
    {p: "Inseparable Stability", d: "Unlike some German prefixes that detach in conjugation, ver- remains fused to its root. This stability contrasts with English, where morphemes can sep", c: 27},
    {p: "Morphological vs. Compositional Strategies", d: "German refines meanings through prefixation. Chinese achieves similar semantic complexity through character compounding. Both languages transform simp", c: 27},
    {p: "Negation as Inversion", d: "The un- prefix does not merely negate; it inverts. Where möglich means \"possible,\" unmöglich means \"impossible.\" Where glaublich means \"believable,\" u", c: 28},
    {p: "Shades of Absence", d: "Unbekannt (unknown) is not the same as \"not known.\" It is mysterious, obscure, foreign. Unschuld (innocence) is not merely \"not guilty\" — it is a stat", c: 28},
    {p: "Productive Morphology", d: "Any adjective or noun can take the un- prefix in German, creating predictable negations. This is why German words feel transparent: the system is syst", c: 28},
    {p: "Language-Specific Negation Strategies", d: "Germanic languages prefix negation directly to words. Sino-Tibetan languages use separate negation particles positioned before the word. Both express ", c: 28},
    {p: "Separability and Syntax", d: "The auf- prefix is separable: it detaches from the verb in main clauses and moves to the end. Aufstehen becomes \"ich stehe auf\" — not \"ich aufstehe.\" ", c: 29},
    {p: "Vertical Motion as a Guiding Metaphor", d: "Auf- means upward, opening, beginning. This manifests as rising (aufstehen), opening (aufmachen), emerging from confusion (Aufklärung), standing out (", c: 29},
    {p: "Transformation Through Activation", d: "Aufmachen (to open) comes from machen (to make). Aufpassen (to pay attention) comes from passen (to fit). The auf- prefix activates these verbs, givin", c: 29},
    {p: "Word Order as a Grammatical Device", d: "German uses position to express meaning. Separable prefixes move to sentence-final position in main clauses. This is not a flaw; it is an elegant stru", c: 29},
    {p: "Outgoingness as Completion", d: "The aus- prefix expresses moving outward and completion. To go out (ausgehen), to endure to the end (aushalten), to choose out (aussuchen). The outwar", c: 30},
    {p: "Concreteness Extending to Abstraction", d: "Aus- begins with literal exits (ausgehen, Ausgang as a physical door) and extends into abstract territory (Ausdruck as expression, Ausnahme as excepti", c: 30},
    {p: "Separability and Portability", d: "Like auf-, aus- is separable. Words split in conjugation: \"ich gehe aus\" not \"ich ausgehe.\" This allows verbs to maintain semantic flexibility while e", c: 30},
    {p: "Extraction and Manifestation", d: "Aus- often suggests pulling something out or making it visible: expression (pressed out), exception (taken out), appearance (seen outward). The prefix", c: 30},
    {p: "Separable Prefixes", d: "German allows verbs to split: the prefix moves to the end in present tense. \"Ich lade dich ein\" — the invitation is suspended until the final word.", c: 31},
    {p: "Directional Morphology", d: "The ein- prefix transforms verbs by adding a directional component: inward movement, transformation, inclusion.", c: 31},
    {p: "Cross-Linguistic Parallels", d: "Chinese uses 入 (rù, enter) as a character rather than a prefix, but achieves identical meaning-making through composition.", c: 31},
    {p: "Productivity and Generativity", d: "New ein- compounds continue to be created in modern German, showing that this morphological pattern is alive and generative.", c: 31},
    {p: "Directional Opposites", d: "Ein- and ab- are mirror prefixes: one draws in, the other sends away.", c: 32},
    {p: "Separation and Division", d: "The ab- prefix marks not just physical departure but conceptual separation: voting, cancellation, sectioning.", c: 32},
    {p: "Temporal Meaning", d: "Time and light depart; language encodes this in the word \"Abend\" (evening, the going-away of day).", c: 32},
    {p: "Metaphorical Extension", d: "From physical separation (cutting, hanging) to social actions (voting, canceling) to emotional states (farewell).", c: 32},
    {p: "Transparent Structure", d: "German compounds reveal their meaning through component parts. A \"Kühlschrank\" is explicitly a \"cool-cupboard.\"", c: 33},
    {p: "Metaphorical Classification", d: "A glove is a \"hand-shoe\"; a turtle is a \"shield-toad.\" Compounds reveal how a culture conceptualizes relationships.", c: 33},
    {p: "Head-Final Structure", d: "The final word determines grammatical properties (gender, number, case). The head word comes at the end.", c: 33},
    {p: "Infinite Productivity", d: "New compounds can be created on the fly and understood immediately without memorization.", c: 33},
    {p: "Function Over Form", d: "German defines objects by what they do, not what they are. Flugzeug (flying-stuff), Fahrzeug (driving-stuff), Spielzeug (playing-stuff). The name reve", c: 34},
    {p: "Suffix-Based Compounding", d: "Zeug and Werk are productive suffixes that attach to verbal roots and noun roots to create objects. This is morphology in real-time, a system for buil", c: 34},
    {p: "Stability Through Abstraction", d: "Feuerzeug (lighter) has remained the name even as technology changed from flint-and-steel to electric. The word\'s abstract functional meaning—\"fire-ma", c: 34},
    {p: "Categorical Elevation Through Werk", d: "While Zeug names functional objects neutrally, Werk elevates: Handwerk (craft), Kunstwerk (artwork), Meisterwerk (masterpiece). Werkmarks quality, tra", c: 34},
    {p: "The -ung Suffix Creates Action Nouns", d: "Any verb can be transformed into a noun by adding -ung to its root: bilden → Bildung (education), erfahren → Erfahrung (experience). This suffix is re", c: 35},
    {p: "All -ung Nouns Are Feminine", d: "Without exception, every noun formed with the -ung suffix is feminine: die Bildung, die Hoffnung, die Wohnung. This is the first completely reliable G", c: 35},
    {p: "-ung Captures Process and Result Together", d: "The suffix doesn\'t distinguish between the action and its outcome: Ordnung means both the process of ordering and the state of being ordered. This amb", c: 35},
    {p: "From Transitive to Abstract Noun", d: "When a verb is transformed by -ung, the focus shifts from the action itself to the result or state that action creates, making the internal world of i", c: 35},
    {p: "-heit and -keit Create Abstract Qualities", d: "These suffixes transform adjectives into nouns representing their abstract qualities: schön → Schönheit (beauty), möglich → Möglichkeit (possibility),", c: 36},
    {p: "All -heit and -keit Nouns Are Feminine", d: "Like the -ung suffix before it, these suffixes always create feminine nouns: die Freiheit, die Schönheit, die Möglichkeit, die Wirklichkeit. This seco", c: 36},
    {p: "-keit Follows Adjectives Ending in -lich or -ig", d: "While most adjectives take -heit, those ending in -lich or -ig take -keit instead: möglich → Möglichkeit, wirklich → Wirklichkeit, einsam → Einsamkeit", c: 36},
    {p: "Qualities Become Principles", d: "When an adjective is transformed through -heit or -keit, it transcends description and becomes a fundamental principle worthy of contemplation and phi", c: 36},
    {p: "The -schaft Suffix Creates Collective Nouns", d: "This suffix transforms individual entities into the whole body or state they create: Freund → Freundschaft (friendship), Wissenschaft (science from \"k", c: 37},
    {p: "All -schaft Nouns Are Feminine", d: "Every noun with the -schaft suffix is feminine: die Freundschaft, die Gesellschaft, die Wirtschaft, die Leidenschaft. This is the third absolute gende", c: 37},
    {p: "-schaft Bridges Individual to Collective", d: "The suffix encodes a conceptual transformation from singular to plural, from personal to social, from thing to system. Landschaft transforms \"land\" in", c: 37},
    {p: "-schaft Words Carry Deep Philosophical Weight", d: "Words like Freundschaft, Leidenschaft, and Gesellschaft represent entire ethical and social systems, not mere collections of individuals. This reflect", c: 37},
    {p: "The -lich Suffix Creates Quality Adjectives", d: "This suffix transforms nouns, verbs, and other words into adjectives describing manner or quality: Freund → freundlich (friendly), gefährlich (dangero", c: 38},
    {p: "The -bar Suffix Means \"Capable of Being\"", d: "This suffix attaches to verbs to create adjectives expressing capability or possibility: wunderbar (wonderful—capable of wonder), machbar (doable). It", c: 38},
    {p: "The -ig Suffix Describes Possession of a Quality", d: "This suffix adds a sense of \"having\" or \"full of\": wichtig (important—having weight), durstig (thirsty—having thirst). It is particularly common with ", c: 38},
    {p: "Adjective Suffixes Unlock Millions of Expressions", d: "These three suffixes are extraordinarily productive, allowing German speakers to create or understand new adjectives intuitively. When combined with t", c: 38},
    {p: "The -er Agent Suffix", d: "Attaches to verb stems to create nouns naming the person who performs the action. Lehren → Lehrer (teacher), arbeiten → Arbeiter (worker). This suffix", c: 39},
    {p: "The -in Feminine Marker", d: "Transforms masculine agent nouns into their feminine equivalents. Lehrer → Lehrerin, Arbeiter → Arbeiterin. The suffix makes gender visible and has be", c: 39},
    {p: "Variant -ler Form", d: "A modern variant of -er used especially with compound nouns (Wissenschaft + ler = Wissenschaftler). This form became common in the 19th and 20th centu", c: 39},
    {p: "The Problem of Gender", d: "Agent nouns raise fundamental questions about language and representation. How we mark gender in professions reflects and shapes how we recognize diff", c: 39},
    {p: "The ent- Prefix Marks Removal", d: "Entdecken (discover) = ent- (remove) + decken (cover). The prefix marks the uncovering of what was hidden, revealing the action as a removal of obscur", c: 40},
    {p: "Metaphorical Consistency", d: "The prefix appears across many verbs, each expressing removal in different forms: entscheiden (decide = cut away options), entschuldigen (apologize = ", c: 40},
    {p: "Inseparable in Grammar", d: "Unlike some German prefixes that can separate from the verb in conjugation, ent- remains permanently attached. This grammatical unity reflects semanti", c: 40},
    {p: "Grammar as Philosophy", d: "German\'s ent- prefix encodes a way of thinking about the world: revelation over creation, uncovering over making new, clarity over obscurity. The gram", c: 40},
    {p: "The zer- Prefix Marks Fragmentation", d: "Unlike ent- (removal) or reversal prefixes, zer- means breaking into pieces. Zerbrechen (shatter), zerfallen (decay), zerstören (destroy), zerreissen ", c: 41},
    {p: "Violent and Complete Destruction", d: "English has no direct equivalent for zer-. While English uses \"dis-\" or \"de-\", none capture the specific sense of violent fragmentation. This makes ze", c: 41},
    {p: "Gradual and Sudden Breaking", d: "The prefix appears in verbs of sudden violence (zerbrechen = shatter) and slow decay (zerfallen = crumble). The metaphor is unified across both: from ", c: 41},
    {p: "Inseparable and Inevitable", d: "Like ent-, the zer- prefix is inseparable from its verb. This grammatical permanence reflects semantic truth: once something is zerstört, it remains b", c: 41},
    {p: "Spatial Prefixes Becoming Temporal and Abstract", d: "An-, bei-, and mit- begin as prepositions expressing location in space. As prefixes, they transform these spatial concepts into temporal (anfangen = b", c: 42},
    {p: "Three Directional Orientations", d: "An- points toward a location or target (at, toward). Bei- expresses proximity and accompanying presence (by, near, alongside). Mit- embodies joint par", c: 42},
    {p: "Inseparability and Productivity", d: "Unlike auf- and aus-, the prefixes an-, bei-, and mit- are inseparable: they do not detach during conjugation. This stability allows them to be highly", c: 42},
    {p: "Ancient Spatial Logic Preserved", d: "These prefixes are among the oldest elements of Germanic. Their survival and productivity reveals how foundational spatial thinking is to language. Ev", c: 42},
    {p: "Spatial-Temporal Duality", d: "Vor- (before), nach- (after), über- (over), and unter- (under) encode spatial position but extend into temporal sequence and abstract hierarchy. The l", c: 43},
    {p: "Separability Reflects Abstraction Degree", d: "Some vor-/nach- compounds are separable (vorstellen can split: \"stelle vor\"), while über- and unter- are typically inseparable (übersetzen never split", c: 43},
    {p: "Metaphorical Coherence", d: "Vorstellen (to place before) becomes both \"to introduce\" and \"to imagine.\" Übersetzen (to carry over) becomes \"to translate.\" Unterschied (under-cut) ", c: 43},
    {p: "Universal Conceptual Foundations", d: "Across languages, translation is metaphorically a transformation or crossing (German übersetzen, Chinese 翻译 fānyì). Difference is conceptually a cutti", c: 43},
    {p: "Repetition as Elevation", d: "The spiral is not a circle. When you", c: 44},
    {p: "Return as Recognition", d: "", c: 44},
    {p: "Continuation as Resistance", d: "", c: 44},
    {p: "Giving Back Sustains the Spiral", d: "", c: 44},
    {p: "Be- Makes Verbs Transitive", d: "The prefix", c: 45},
    {p: "Er- Marks Achievement", d: "The prefix", c: 45},
    {p: "Ge- Gathers Multiplicity into Unity", d: "The prefix", c: 45},
    {p: "Ancient Prefixes, Silent Power", d: "Be-, er-, ge- are among the oldest prefixes in German, yet they operate almost invisibly in everyday speech. Their power lies in their subtlety: they ", c: 45},
    {p: "Prefix Layering:", d: "Multiple prefixes can layer together (un- + abhängig + -keit) to create meaning through systematic transformation.", c: 46},
    {p: "Compound Building:", d: "German compounds show how roots join spatially (hand-schuh-fach, Tür-klinke) to create new concrete meanings.", c: 46},
    {p: "Cross-Linguistic Parallels:", d: "Both German and Chinese use prefix/radical systems to build meaning from spatial and conceptual primitives, revealing universal patterns in language.", c: 46},
    {p: "Decomposition Mastery:", d: "Every German word can be read by finding the rightmost head, then tracing leftward through prefixes, roots, and suffixes to reconstruct the entire mea", c: 46},
    {p: "Phase 2 Completion:", d: "You now control 13 core prefixes, 5 core suffixes, and understand how they combine with roots and compounds to create virtually unlimited German vocab", c: 46},
    {p: "Phase 1", d: "taught you to", c: 46},
    {p: "HEAR", d: "German.", c: 46},
    {p: "Phase 2", d: "taught you to", c: 46},
    {p: "SEE THROUGH", d: "it.", c: 46},
    {p: "Phase 3", d: "will teach you to", c: 46},
    {p: "BUILD WITH", d: "it.", c: 46},
    {p: "Gender is Logic, Not Random", d: "Eighty percent of German noun genders can be predicted from suffixes and semantic patterns. Memorization is not necessary; understanding the system is", c: 47},
    {p: "The Suffix Rule", d: "Words ending in -ung, -heit, -keit, -schaft are always feminine. Words ending in -chen, -lein are always neuter. Words ending in -er are usually mascu", c: 47},
    {p: "The Semantic Pattern", d: "Solid, durable furniture is usually masculine. Abstract qualities ending in -ung are feminine. Days, months, seasons are masculine. Understanding mean", c: 47},
    {p: "Chinese Comparison", d: "Chinese has no grammatical gender at all. 这个 (zhège) works for everything. It\'s a different solution to the same problem: how do you coordinate agreem", c: 47},
    {p: "Irregularity Tells History", d: "The verb \"to be\" is irregular not because the language is broken, but because it\'s the most fundamental verb. The most commonly used words change the ", c: 48},
    {p: "Three Roots Merged", d: "German\'s sein draws from three different PIE roots: *bheu- (become), *es- (exist), and *wes- (dwell). You can see the merger in the conjugation table ", c: 48},
    {p: "Suppletion", d: "Using forms from different roots in the same verb\'s conjugation is called suppletion. It\'s common in ancient languages. As languages modernize, they t", c: 48},
    {p: "Chinese Alternative", d: "Chinese solves this differently. The verb 是 (shì) never changes, never conjugates. All tense and aspect information comes from particles and context. ", c: 48},
    {p: "Regular vs. Irregular", d: "Haben is regular because it\'s younger and less fundamental than sein. Older, more-used verbs are more irregular. Frequency drives irregularity.", c: 49},
    {p: "Possession vs. Being", d: "German uses haben for abstract states English reserves for sein: \"I have hunger\" instead of \"I am hungry.\" This reflects different ways of conceptuali", c: 49},
    {p: "Auxiliary Function", d: "Haben serves as an auxiliary verb, combining with past participles to form perfect tenses. Sein also does this, but with motion and change-of-state ve", c: 49},
    {p: "Predictable Conjugation", d: "Unlike sein, haben follows regular patterns. Remove the -n from the infinitive to get the stem, then add regular endings. This is how most German verb", c: 49},
    {p: "The Verb-to-End Rule Defines Subordination", d: "Whenever a subordinating conjunction (weil, dass, obwohl) introduces a clause, the conjugated verb must move to the very end: \"Ich bin glücklich, weil", c: 63},
    {p: "Weil Introduces Reasons and Explanations", d: "This conjunction answers \"why?\" and always introduces a causal relationship: \"Ich bin müde, weil ich nicht gut schlafe\" (I am tired because I don\'t sl", c: 63},
    {p: "Dass Reports Speech and Propositions", d: "Dass introduces indirect speech, reported thoughts, and complete propositions: \"Er sagt, dass er morgen kommt\" (He says that he is coming tomorrow). I", c: 63},
    {p: "Obwohl Creates Concessive Contrast", d: "This conjunction admits a fact while contrasting it with the main clause: \"Obwohl es kalt ist, gehe ich raus\" (Although it is cold, I go outside). It ", c: 63},
    {p: "Coordinating Conjunctions Connect Equals", d: "Und, aber, and denn sit between equal clauses (main clause + main clause), creating a coordinate relationship where both clauses maintain their indepe", c: 64},
    {p: "No Word Order Change with Coordination", d: "Unlike subordinating conjunctions that push the verb to the end, coordinating conjunctions leave word order untouched. Both clauses maintain standard ", c: 64},
    {p: "Und = Addition and Continuation", d: "This conjunction simply adds one idea to another without modification: \"Ich bin intelligent und fleißig\" (I am intelligent and industrious). It is neu", c: 64},
    {p: "Aber and Denn Express Contrast and Cause", d: "Aber introduces contrast and opposition: \"Ich bin intelligent, aber faul\" (I am intelligent but lazy). Denn introduces explanation and reason within c", c: 64},
    {p: "The Subjunctive as Psychological Distance", d: "Konjunktiv II is not just grammar; it\'s a mood that marks unreality, wishes, and hypotheticals. Every subjunctive form signals: \"This is imagined, not", c: 67},
    {p: "Three Core Subjunctive Forms Survived the Language", d: "", c: 67},
    {p: "Politeness Through Grammatical Softening", d: "Comparing", c: 67},
    {p: "Modal Verbs in the Subjunctive Shift Meaning", d: "", c: 67},
    {p: "Konjunktiv I Marks Reported Distance", d: "When speech becomes indirect, the mood shifts to signal that these are not the speaker\'s direct words.", c: 68},
    {p: "Three Forms Survived Because They Sound Subjunctive", d: "Most Konjunktiv I forms are identical to the indicative, so they\'re invisible. Only", c: 68},
    {p: "The Pronoun Shift is Crucial", d: "In indirect speech, pronouns shift perspective.", c: 68},
    {p: "Konjunktiv I is Primarily Journalistic", d: "In newspapers and formal reporting, Konjunktiv I signals journalistic distance: \"The government declared that the situation", c: 68},
    {p: "Reflexive Pronouns Mirror the Subject", d: "In reflexive verbs, the same person performs and receives the action.", c: 70},
    {p: "Accusative vs. Dative Reflexive Pronouns", d: "Accusative (", c: 70},
    {p: "Obligatory vs. Optional Reflexivity", d: "Some verbs", c: 70},
    {p: "German Marks Reflexivity Explicitly, English Often Doesn\'t", d: "German always includes the reflexive pronoun, while English often omits the \"myself\" or \"yourself.\" This makes German more grammatically transparent.", c: 70},
    {p: "Lassen Has Four Distinct Meanings Depending on Context", d: "Permission:", c: 71},
    {p: "Lassen Always Takes an Infinitive, Never a Past Participle", d: "The verb following lassen must stay in its infinitive form:", c: 71},
    {p: "Commission Uses Dative Reflexive + Direct Object", d: "", c: 71},
    {p: "Lassen Core Concept: Releasing Agency or Responsibility", d: "All four meanings share the idea of the subject releasing control, permission, or responsibility to another entity or force. Understanding this unifie", c: 71},
    {p: "Um...zu Expresses Purpose and Intention", d: "", c: 72},
    {p: "Ohne...zu Describes an Action Performed Without Doing Something Else", d: "", c: 72},
    {p: "Anstatt...zu (or Statt...zu) Presents an Alternative Action", d: "", c: 72},
    {p: "Critical Rule: Both Clauses Must Have the Same Subject", d: "All three constructions (", c: 72},
    {p: "Ablaut in Action", d: "Strong verbs use vowel changes (ablaut) to show tense. The ei→ie→ie pattern is ancient, tracing back to Proto-Indo-European.", c: 79},
    {p: "Three Forms to Learn", d: "For each strong verb, memorize: infinitive, past tense, past participle. This precision reveals how the verb functions across time.", c: 79},
    {p: "The River Metaphor", d: "Like a river changing course, strong verbs change their vowels but remain recognizably themselves. The root is visible in each form.", c: 79},
    {p: "Core Verbs", d: "The ei→ie→ie family contains some of the most essential verbs in German: to write, to stay, to climb, to be silent.", c: 79},
    {p: "The i→a→u Pattern", d: "This vowel cascade is consistent across the entire family. Once you learn the pattern, you can predict the forms.", c: 80},
    {p: "Essential Verbs", d: "Trinken, singen, finden — these are verbs of daily life. They anchor your German vocabulary in the most practical concerns: nourishment, expression, d", c: 80},
    {p: "Larger Family", d: "The i→a→u family is larger than the ei→ie→ie family, with many more verbs following this pattern.", c: 80},
    {p: "Metaphorical Range", d: "These verbs carry both literal and metaphorical meanings. To find is to discover. To bind is to obligate. To win is to achieve.", c: 80},
    {p: "The Passive Revolution", d: "Academic German deprioritizes the subject through passive voice. The discovery matters more than the discoverer.", c: 95},
    {p: "Nominalization", d: "Verbs become nouns. Actions become things. This creates abstract, precise terminology.", c: 95},
    {p: "Hedging and Qualification", d: "Academic German is full of \"appears,\" \"suggests,\" \"might be.\" This is not weakness; it is precision.", c: 95},
    {p: "The Complex Sentence", d: "Academic prose builds long, intricate sentences that mirror the complexity of thought itself. Each clause builds on the others until the final verb ar", c: 95},
    {p: "Emotional Precision", d: "Literary German creates words for feelings that have no English equivalents.", c: 96},
    {p: "Paradox and Tension", d: "Great German literature often holds opposites in tension: the abyss and shelter, the fleeting and the eternal, tearing and rising.", c: 96},
    {p: "Spiritual Vocabulary", d: "German literature is saturated with words about the soul, transcendence, transformation. Language reaches toward what cannot be easily said.", c: 96},
    {p: "The Interior Landscape", d: "Literary German maps the terrain of the soul with precision. Characters move through emotional landscapes as vividly as they move through physical one", c: 96},
    {p: "Headline Grammar", d: "Compressed, economical, using present tense to create immediacy. Word order is flexible to maximize impact.", c: 97},
    {p: "Framing Through Language", d: "Word choice shapes how events are understood.", c: 97},
    {p: "The Politics of Attribution", d: "Who is quoted? Whose", c: 97},
    {p: "Immediacy and Urgency", d: "Newspaper German creates the sense that events are happening now, demanding response, requiring action.", c: 97},
    {p: "Filler Words as Meaning", d: "Fillers like", c: 98},
    {p: "Grammar in Motion", d: "Spoken German contracts, inverts, bends. Grammar serves the music of speech, not rigid rules.", c: 98},
    {p: "Hedging and Approximation", d: "Spoken German is full of words that qualify and approximate. This is not vagueness but honesty about the limits of language.", c: 98},
    {p: "Intonation as Meaning", d: "The same word means different things depending on tone, stress, context. Speech carries meaning that writing cannot.", c: 98}
  ]
};
